AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Market Place SaaS - entitlement and subscription portal (qs-1s3j136e1)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Deploy AWS Market Place SaaS entitlement and subscription portal"
  AWS::CloudFormation::Interface:
    ParameterLabels:
      AWSMarketplaceMeteringRecordsTableName:
        default: "Metering Records DynamoDB Table Name"
      CreateRegistrationWebPage:
        default: "Create Registration Page"
      EntitlementSNSTopic:
        default: "Entitlements SNS Topic ARN"
      MarketplaceTechAdminEmail:
        default: "Admin Email Address"
      NewSubscribersTableName:
        default: "New Subscribers DynamoDB Table Name"
      ProductCode:
        default: "Product Code"
      SubscriptionSNSTopic:
        default: "Subscriptions SNS Topic ARN"
      TypeOfSaaSListing:
        default: "SaaS Pricing Model"
      WebsiteS3BucketName:
        default: ""
      # AWS IA configuration
      ArtifactBucketName:
        default: Artifact S3 bucket name
    ParameterGroups:
      - Label:
          default: AWS Infrastructure and Automation configuration
        Parameters:
          - TypeOfSaaSListing
          - CreateRegistrationWebPage
          - WebsiteS3BucketName
          - ProductCode
          - SubscriptionSNSTopic
          - EntitlementSNSTopic
          - NewSubscribersTableName
          - AWSMarketplaceMeteringRecordsTableName
          - MarketplaceTechAdminEmail
      - Label:
          default: AWS Infrastructure and Automation configuration
        Parameters:
          - ArtifactBucketName
Parameters:
  AWSMarketplaceMeteringRecordsTableName:
    Default: AWSMarketplaceMeteringRecords
    Description: "Use a custom value for this Metering Records Table. Value must be unique per product. Default value provided."
    Type: String
  CreateRegistrationWebPage:
    AllowedValues:
      - "true"
      - "false"
    Default: "true"
    Description: "A registration website page will be created and hosted via AWS CloudFront. If you have your own custom registration page select 'false'. Default value provided"
    Type: String
  EntitlementSNSTopic:
    Description: "If your product is a SaaS Contract use the entitelement SNS topic provided from AWS Marketplace at the time of limited listing publish."
    Type: String
  MarketplaceTechAdminEmail:
    Type: String
    Description: "Provided the email address that will receive SNS notifications for new customer registrations, entitlement changes, and subscription events."
  NewSubscribersTableName:
    Default: AWSMarketplaceSubscribers
    Description: "Use a custom value for the New Subscribers Table. Value must be unique per product. Default value provided."
    Type: String
  ProductCode:
    Description: "Enter the product code provided from AWS Marketplace at the time of limited listing publish."
    Type: String
  SubscriptionSNSTopic:
    Description: "If your product is a SaaS Subscription or Saas Contract with Subscription use the entitlement SNS topic provided from AWS Marketplace at the time of limited listing publish."
    Type: String
  TypeOfSaaSListing:
    AllowedValues:
      - contracts_with_subscription
      - contracts
      - subscriptions
    Default: contracts_with_subscription
    Description: "Select one of the allowed values for the SaaS pricing model of your product. Default value provided."
    Type: String
  WebsiteS3BucketName:
    Type: String
    Description: "Provide the S3 bucket that will hold the static HTML registration page files. If this bucket does not exist it will be created"
  # Integration and Automation location parameters
  ArtifactBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Staging bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    # TODO: nitpick the name and wording here
    Description: S3 bucket name for where the arifacts are housed. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
Conditions:
  CreateRegistrationWebPageCond: !Equals
    - !Ref CreateRegistrationWebPage
    - true

Resources:
  SampleApp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.amazonaws.com/cloudformation-aws-marketplace-saas/submodules/sam/packaged.yaml"
      Parameters:
        AWSMarketplaceMeteringRecordsTableName: !Ref AWSMarketplaceMeteringRecordsTableName
        CreateRegistrationWebPage: !Ref CreateRegistrationWebPage
        EntitlementSNSTopic: !Ref EntitlementSNSTopic
        MarketplaceTechAdminEmail: !Ref MarketplaceTechAdminEmail
        NewSubscribersTableName: !Ref NewSubscribersTableName
        ProductCode: !Ref ProductCode
        SubscriptionSNSTopic: !Ref SubscriptionSNSTopic
        TypeOfSaaSListing: !Ref TypeOfSaaSListing
        WebsiteS3BucketName: !If [CreateRegistrationWebPageCond, !Ref WebsiteS3BucketName, !Ref AWS::NoValue] 

