AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Market Place SaaS - entitlement and subscription portal (qs-1s3j136e1)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Deploy AWS Market Place SaaS entitlement and subscription portal"
  AWS::CloudFormation::Interface:
    ParameterLabels:
      AWSMarketplaceMeteringRecordsTableName:
        default: "Use a custom value for this Metering Records Table. Value must be unique per product. Default value provided."
      CreateRegistrationWebPage:
        default: "A registration website page will be created and hosted via AWS CloudFront. If you have your own custom registration page select 'false'. Default value provided"
      EntitlementSNSTopic:
        default: "If your product is a SaaS Contract use the entitelement SNS topic provided from AWS Marketplace at the time of limited listing publish."
      MarketplaceTechAdminEmail:
        default: ""
      NewSubscribersTableName:
        default: "Use a custom value for the New Subscribers Table. Value must be unique per product. Default value provided."
      ProductCode:
        default: "Enter the product code provided from AWS Marketplace at the time of limited listing publish."
      SubscriptionSNSTopic:
        default: "If your product is a SaaS Subscription or Saas Contract with Subscription use the entitlement SNS topic provided from AWS Marketplace at the time of limited listing publish."
      TypeOfSaaSListing:
       default: "Select one of the allowed values for the SaaS pricing model of your product. Default value provided."
      WebsiteS3BucketName:
        default: ""
      MarketplaceIntegrationApplicationARN:
        default: "(Provided by AWS Market Place) ARN for Marketplace integration SAM app."
      ArtifactBucketName:
        default: Artifact S3 bucket name
#    # AWS IA configuration
#      QSS3BucketName:
#        default: Quick Start S3 bucket name
#      QSS3BucketRegion:
#        default: Quick Start S3 bucket region
#      QSS3KeyPrefix:
#        default: Quick Start S3 key prefix
    ParameterGroups:
      - Label:
          default: AWS Infrastructure and Automation configuration
        Parameters:
          - AWSMarketplaceMeteringRecordsTableName
          - CreateRegistrationWebPage
          - EntitlementSNSTopic
          - MarketplaceTechAdminEmail
          - NewSubscribersTableName
          - ProductCode
          - SubscriptionSNSTopic
          - TypeOfSaaSListing
          - WebsiteS3BucketName
#     - Label:
#        default: AWS Infrastructure and Automation configuration
#      Parameters:
#        - QSS3BucketName
#        - QSS3KeyPrefix
#        - QSS3BucketRegion
Parameters:
  AWSMarketplaceMeteringRecordsTableName: 
    Default: AWSMarketplaceMeteringRecords
    Description: "Use a custom value for this Metering Records Table. Value must be unique per product. Default value provided."
    Type: String
  CreateRegistrationWebPage: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "A registration website page will be created and hosted via AWS CloudFront. If you have your own custom registration page select 'false'. Default value provided"
    Type: String
  EntitlementSNSTopic: 
    Description: "If your product is a SaaS Contract use the entitelement SNS topic provided from AWS Marketplace at the time of limited listing publish."
    Type: String
  MarketplaceTechAdminEmail: 
    Type: String
    Description: "Provided the email address that will receive SNS notifications for new customer registrations, entitlement changes, and subscription events."
  NewSubscribersTableName: 
    Default: AWSMarketplaceSubscribers
    Description: "Use a custom value for the New Subscribers Table. Value must be unique per product. Default value provided."
    Type: String
  ProductCode: 
    Description: "Enter the product code provided from AWS Marketplace at the time of limited listing publish."
    Type: String
  SubscriptionSNSTopic: 
    Description: "If your product is a SaaS Subscription or Saas Contract with Subscription use the entitlement SNS topic provided from AWS Marketplace at the time of limited listing publish."
    Type: String
  TypeOfSaaSListing: 
    AllowedValues: 
      - contracts_with_subscription
      - contracts
      - subscriptions
    Default: contracts_with_subscription
    Description: "Select one of the allowed values for the SaaS pricing model of your product. Default value provided."
    Type: String
  WebsiteS3BucketName:
    Type: String
    Description: "Provide the S3 bucket that will hold the static HTML registration page files. If this bucket does not exist it will be created"
  MarketplaceIntegrationApplicationARN:
    Type: String
    Description: "AWS Market Place integration application provided by AWS Market Place."
  # Integration and Automation location parameters
  ArtifactBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Staging bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    # TODO: nitpick the name and wording here
    Description: S3 bucket name for where the arifacts are housed. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
Conditions:
  CreateRegistrationWebPageCond: !Equals
    - !Ref CreateRegistrationWebPage
    - true

Resources:
  SampleApp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.amazonaws.com/cloudformation-aws-marketplace-saas/submodules/sam/packaged.yaml"
      Parameters:
        AWSMarketplaceMeteringRecordsTableName: !Ref AWSMarketplaceMeteringRecordsTableName
        CreateRegistrationWebPage: !Ref CreateRegistrationWebPage
        EntitlementSNSTopic: !Ref EntitlementSNSTopic
        MarketplaceTechAdminEmail: !Ref MarketplaceTechAdminEmail
        NewSubscribersTableName: !Ref NewSubscribersTableName
        ProductCode: !Ref ProductCode
        SubscriptionSNSTopic: !Ref SubscriptionSNSTopic
        TypeOfSaaSListing: !Ref TypeOfSaaSListing
        WebsiteS3BucketName: !If [CreateRegistrationWebPageCond, !Ref WebsiteS3BucketName, !Ref AWS::NoValue] 

